### ISSUE TITLE
Hi there is some suggestions for you.

### ISSUE THREAD

**Issue by 1100111GTH** [BDR-Pro/EnigmaLang#1]
I'm happy to see a python obfuscate project updated by you, the gihub repo doesn't have much younger or maybe still upgrade projects, except Pyarmor. i think you should learn from them and you can do better.

**Comment by 1100111GTH** [comment]
Tell me what the bug is and I will try to help you.

**Comment by BDR-Pro** [comment]
it was working until i want to make it with itreations 
failed
return back to the and failed

probably i need just to check out to the first commit lol

**Comment by BDR-Pro** [comment]
PS C:\Users\bdrkh\Documents\Python\EnigmaLang> & C:/Users/bdrkh/AppData/Local/Programs/Python/Python312/python.exe c:/Users/bdrkh/Documents/Python/EnigmaLang/test_code/helloworld_obfuscated.py 550c6f8511f688c051afa136e2a215b88312d774e06f262708734ba6b8d42c23
Traceback (most recent call last):
  File "c:\Users\bdrkh\Documents\Python\EnigmaLang\test_code\helloworld_obfuscated.py", line 7, in <module>
    exec(loaded_bytecode)
  File "filename", line 3394, in <module>
  File "filename", line 3389, in decrypt_and_execute_dfjqBWwQSq
  File "C:\Users\bdrkh\AppData\Local\Programs\Python\Python312\Lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
PS C:\Users\bdrkh\Documents\Python\EnigmaLang>

**Comment by 1100111GTH** [comment]
Sorry, I'm quite busy these days, when I'm free, I'll try.
